### ISSUE TITLE
请问审核大概什么时间段可以好呢？如果我要用引入lib形式，应该引入哪个文件

### ISSUE THREAD

**Issue by Yihaoer** [alibaba/GCanvas#108]
请问审核大概什么时间段可以好呢？如果我要用引入lib形式，应该引入哪个文件，我试过把gcanvans下的文件都引进来，但是不知道Fresco版本，谢谢

**Comment by luckzhiwei** [comment]
1.  Fresco版本使用1.8.0。现在由于master分支的文件结构暂时有些问题，请使用 [1.1.0](https://github.com/alibaba/GCanvas/tree/1.1.0 )版本来进行以lib库的依赖
  2. 使用lib形式依赖，用weex进行开发，需要依赖的是工程下的 GCanvas/brgides/weex-bridge/android/weex-brigde 这个library工程。具体使用方式可以见[Guide_Android_Setup_Weex](https://github.com/alibaba/GCanvas/blob/1.1.0/docs/Guide_Android_Setup_Weex.md)。依赖方式就是使用外部工程依赖。
3. 发布到maven已经在日程中，请耐心等待

**Comment by Yihaoer** [comment]
> 1. Fresco版本使用1.8.0。现在由于master分支的文件结构暂时有些问题，请使用 [1.1.0](https://github.com/alibaba/GCanvas/tree/1.1.0)版本来进行以lib库的依赖
> 2. 使用lib形式依赖，用weex进行开发，需要依赖的是工程下的 GCanvas/brgides/weex-bridge/android/weex-brigde 这个library工程。具体使用方式可以见[Guide_Android_Setup_Weex](https://github.com/alibaba/GCanvas/blob/1.1.0/docs/Guide_Android_Setup_Weex.md)。依赖方式就是使用外部工程依赖。
> 3. 发布到maven已经在日程中，请耐心等待

工程下没有 GCanvas/brgides/weex-bridge/android/weex-brigde 路径，我看到的只有GCanvas，然后子文件是android、core、ios

**Comment by luckzhiwei** [comment]
git clone && cd GCanvas && git checkout 1.1.0 （切换到1.1.0 tag）
然后在根目录下你看看有没有 GCanvas/android/weex-bridge/android/weex-bridge/
![image](https://user-images.githubusercontent.com/9296681/69705078-bf5e8800-112f-11ea-9367-9de6c72f9953.png)

**Comment by Yihaoer** [comment]
> git clone && cd GCanvas && git checkout 1.1.0 （切换到1.1.0 tag）
> 然后在根目录下你看看有没有 GCanvas/android/weex-bridge/android/weex-bridge/
> ![image](https://user-images.githubusercontent.com/9296681/69705078-bf5e8800-112f-11ea-9367-9de6c72f9953.png)

收到，谢谢！
