### ISSUE TITLE
GCanvas on ReactNative  android真机一启动就崩溃，ios绘制图形超级慢

### ISSUE THREAD

**Issue by ruixue521** [alibaba/GCanvas#113]
版本:
 "dependencies": {
    "@gcanvas/core": "^1.0.0",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gcanvas": "0.0.7-dev",
}

正常再次绘制任何线段ios会延迟很久，而且还是累计的，延迟越来越厉害，android响应正常

**Comment by jwxbond** [comment]
能提供下iOS版本信息和demo吗？

**Comment by ruixue521** [comment]
您好：
git clone https://gitee.com/didu2018/GCanvas.git
这是一个新建的项目，里面的代码也是官方案例，

问题：android运行直接崩溃

麻烦帮忙看下这个问题先。

**Comment by ruixue521** [comment]
您好，
ios 除了首次绘制图形外，再次增加图形相当慢，
android 真机 一运行就崩溃，模拟器运行正常，偶尔修个一个text文字也会崩溃，
麻烦您看下

git clone https://gitee.com/didu2018/GCanvas.git

**Comment by jwxbond** [comment]
这Demo无法运行。

**Comment by flyskywhy** [comment]
@ruixue521 这个 [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas)  可以在 Android 真机上运行的，而且绘图速度很快。 iOS 绘图的确较慢。

由于 Alibaba 已经 [feat: delete weex bridge & reactive bridge](https://github.com/alibaba/GCanvas/commit/1bbee40a16c0c5da58698e2892ba33f836eedb70) ，现在可替之以 [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) 这个 npm 包。

经过几个月的努力， [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) 在 Android 和 iOS 上运行良好， [Changelog.md](https://github.com/flyskywhy/react-native-gcanvas/blob/master/docs/Changelog.md) 中描述了所修复的几个 bug 以及添加的 `feat: support drawImage() from require('some.png') on Android, iOS and Web` 新特性， README.md 中重构了详细的 [Example As Usage](https://github.com/flyskywhy/react-native-gcanvas#example-as-usage) 。

基于 [Performance Test Result](https://github.com/flyskywhy/react-native-gcanvas#performance-test-result) ， 以及 [Convenient With Browser-like canvas APIs](https://github.com/flyskywhy/react-native-gcanvas#convenient-with-browser-like-canvas-apis) 和与之相关的 `<canvas/>` 简易移植后就能运行在 Android 、 iOS 和 Web 上的示例 [react-native-particles-bg](https://github.com/flyskywhy/react-native-particles-bg) ， `@flyskywhy/react-native-gcanvas` 是现在最好的选择 :yum:

**Comment by flyskywhy** [comment]
ruixue521 ， iOS 累计延迟越来越厉害的问题已经在 @flyskywhy/react-native-gcanvas@2.1.2 中解决 😆
