### ISSUE TITLE
什么时候发布新版本的包适配现在最新的weex0.28的SDK啊

### ISSUE THREAD

**Issue by foyel** [alibaba/GCanvas#116]

**Comment by jwxbond** [comment]
现在最新的已经能使用weex 0.28了。

**Comment by foyel** [comment]
> 现在最新的已经能使用weex 0.28了。
你好，请问怎么集成，有文档或者介绍吗？

**Comment by jwxbond** [comment]
https://github.com/alibaba/GCanvas/tree/master/bridges/weex-gcanvas/ios/playground  iOS playground

**Comment by forest606** [comment]
有Android的集成文档吗？
