### ISSUE TITLE
gcanvas这个pod引入还能用吗？

### ISSUE THREAD

**Issue by MagicLinuxRing** [alibaba/GCanvas#117]
Analyzing dependencies
Downloading dependencies
Installing GCanvas (1.1.0)

[!] Error installing GCanvas
[!] /usr/local/bin/git clone https://github.com/alibaba/GCanvas.git /var/folders/3h/c3gybr5x4hgg9dykqj95c7sh0000gp/T/d20191216-12791-11husc1 --template= --single-branch --depth 1 --branch 1.1.0

Cloning into '/var/folders/3h/c3gybr5x4hgg9dykqj95c7sh0000gp/T/d20191216-12791-11husc1'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

我的pod依赖按官方文档来的？外面还能用吗？

**Comment by MagicLinuxRing** [comment]
pod 'WeexGcanvas'
 pod 'WeexPluginLoader'
我是weex项目里面引入的

**Comment by MagicLinuxRing** [comment]
MD，真是垃圾，外网pr都不回复，只能去内网ATA上把这些人炸出来了

**Comment by jwxbond** [comment]
文档里有说明，请参考 http://gitlab.alibaba-inc.com/gcanvas/gcanvas_github_mirror/blob/master/GCanvas/bridges/weex-bridge/ios/playground/Podfile

**Comment by MagicLinuxRing** [comment]
> 文档里有说明，请参考 http://gitlab.alibaba-inc.com/gcanvas/gcanvas_github_mirror/blob/master/GCanvas/bridges/weex-bridge/ios/playground/Podfile

所以就是公司的人用着爽，外面各种不爽，然后就只能喷了，为啥不把这些都公开呢？让社区壮大不是更好吗

**Comment by jwxbond** [comment]
Weex SDK 和 WeexPluginLoader 是Weex团队维护的，需要他们那边协助公开。
