### ISSUE TITLE
这真的又是一个kpi项目吗？

### ISSUE THREAD

**Issue by tailorsira** [alibaba/GCanvas#119]
很生气，很失望。
出于对阿里出品的极度信任，以及社区内阿里大佬的推广，动画技术选型决定采用GCanvas，但是花费了整整一周的时间，搜罗我能搜罗到的所有开源资料，居然还没有把安卓跑通。

先不说文档的细致规范，至少安卓和IOS应该发布一个稳定的release版本，也有其他同学提了这个问题，但是得到的结果是一个内网链接，试问你们已经开源了，非阿里的同学们如何拿到你们内网的链接呢？
本着对自己开源轮子以及开发者负责的精神，你们也要输出一个完整稳定，起码能让开发者在一天内就能跑通demo的资料，但事实上没有。
阿里每次出品开源产品，我都热情高涨，但是狼来了喊了太多遍了，当你真的上手使用产品时，发现来的并不是狼，是个披着羊皮的半成品，这样的半成品导致开发者浪费了大量时间在解决各种bug，责任呢？信任呢？荡然无存。

**Comment by jwxbond** [comment]
感谢你的反馈，你提到的内网链接的问题能具体说下吗？很抱歉，对于Demo运行，请以Weex的容器为主，影响了部分开发者的体验 。Weex的部分可参考https://github.com/alibaba/GCanvas/tree/master/bridges/weex-gcanvas。 另外还有部分跟WeexSDK衔接上有些问题。不依赖WeexSDK的JSBinding的计划推出中。

**Comment by luckzhiwei** [comment]
@tailorsira 感谢你的反馈，该项目weex部分的维护由于人员迭代等其他原因，导致weex相关链路维护的缺失，我们正在重新整理gcanvas的架构，之后会给大家一个完善的release版本

**Comment by flyskywhy** [comment]
@malaxiannv 

由于 Alibaba 已经 [feat: delete weex bridge & reactive bridge](https://github.com/alibaba/GCanvas/commit/1bbee40a16c0c5da58698e2892ba33f836eedb70) ，现在可替之以 [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) 这个 npm 包。

经过几个月的努力， [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) 在 Android 和 iOS 上运行良好， [Changelog.md](https://github.com/flyskywhy/react-native-gcanvas/blob/master/docs/Changelog.md) 中描述了所修复的几个 bug 以及添加的 `feat: support drawImage() from require('some.png') on Android, iOS and Web` 新特性， README.md 中重构了详细的 [Example As Usage](https://github.com/flyskywhy/react-native-gcanvas#example-as-usage) 。

基于 [Performance Test Result](https://github.com/flyskywhy/react-native-gcanvas#performance-test-result) ， 以及 [Convenient With Browser-like canvas APIs](https://github.com/flyskywhy/react-native-gcanvas#convenient-with-browser-like-canvas-apis) 和与之相关的 `<canvas/>` 简易移植后就能运行在 Android 、 iOS 和 Web 上的示例 [react-native-particles-bg](https://github.com/flyskywhy/react-native-particles-bg) ， `@flyskywhy/react-native-gcanvas` 是现在最好的选择 :yum:

PS: 至于说到 kpi 项目，我只能说，现实社会就是如此。之前我也曾经维护了几年另一个阿里后来停止维护的 kpi 项目 [react-web](https://github.com/flyskywhy/react-web) ，我想说的是，在 [react-native-web](https://github.com/necolas/react-native-web) 成熟前的几年里，感谢 react-web 让我过去几年有可靠的 Web 版可用（今年我的项目已切换到 react-native-web 了）。这里再次感谢 GCanvas 项目，让我在几个月的各种 gpu 加速绘图组件搜索、试用后，终于有机会在 react-native 中用上性能良好也易于移植许多现成 web 库的 canvas 组件。
