### ISSUE TITLE
GCanvas Android源码安装的时候libfreetype不能正常加载

### ISSUE THREAD

**Issue by appli456** [alibaba/GCanvas#122]
问题：在使用源码编译Android的时候，只要页面中存在gcanvas的组件都会导致页面降级

原因：core文件夹中的build.gradle文件内，jniLib的路径设置错误，core/src中不存在freetype的so文件，freetype的so文件在core/android文件夹中

**Comment by jwxbond** [comment]
@luckzhiwei  看下freetype库加载问题
