### ISSUE TITLE
Performances for l'on lines drawing.

### ISSUE THREAD

**Issue by farfromrefug** [alibaba/GCanvas#124]
I am looking at your library to create a potential NativeScript plug-in. Right now I use android Canvas and CGContext on iOS. My issue is that it is not so good with very long lines drawing. Did you run some tests with your libs. Especially I am worried about bridge JS C++. When drawing lines with 10000 points or more it would mean 10000 calls to lineTo thus 10000 times the bridge JS /C++. Which in my tests is really slow.
To fix this on my current implementation I used JS FloatArray which can directly share the memory for the array between JS and C++. Can you do something similar? I mean I don't see apis to directly pass lines arrays data

**Comment by jwxbond** [comment]
In this case , use shared memory is a good way to reduce JS bridge to C++. I can be provide as an extension method. Directly pass line array data feature  you can commit Pull Request, That's welcome.

**Comment by farfromrefug** [comment]
@jwxbond Yes that s what i use in Nativescript. Might have a got at testing your lib within Nativescript. THanks
