### ISSUE TITLE
gcanvas  sdk安装失败

### ISSUE THREAD

**Issue by keepmovingon** [alibaba/GCanvas#129]
WXSDKEngine.registerModule("gcanvas", GCanvasWeexModule.class);
WXSDKEngine.registerComponent("gcanvas", WXGCanvasWeexComponent.class);
AS上应该如何正确安装gcanvas

**Comment by jwxbond** [comment]
参考demo中的  https://github.com/alibaba/GCanvas/blob/9d6d67f8c6a6d1e41e3fd730bb3426beee146fba/bridges/weex-gcanvas/android/weex_playground/src/main/java/com/alibaba/weex/WXApplication.java#L90
