### ISSUE TITLE
Library does not support drawimage from other canvas or GCanvas?

### ISSUE THREAD

**Issue by DavidGOrtega** [alibaba/GCanvas#13]
Hi, one of the drawImage features is be able to draw a canvas over another canvas using drawImage. Following the code I can see that the code just only supports images with src member.

Does the library support drawImage from other GCanvas?

**Comment by fREEDtICE** [comment]
Hi, David
Thanks for following GCanvas project.
The bad news is that drawing other GCanvas as a RenderTarget does not
support yet.
The good news is that we are working on it, our plan is to release this
feature on early of May.

Thanks.


2018-03-14 13:28 GMT+08:00 DavidGOrtega <notifications@github.com>:
