### ISSUE TITLE
iOS GCanvas CocoaPods失败

### ISSUE THREAD

**Issue by Luis-X** [alibaba/GCanvas#132]
![image](https://user-images.githubusercontent.com/12946846/75013109-79ab2480-54be-11ea-8f0f-2f0ee706c2a7.png)
![image](https://user-images.githubusercontent.com/12946846/75013126-829bf600-54be-11ea-960b-c741cc25b7f0.png)

macOS: 10.15.3
Xcode: 10

**Comment by Luis-X** [comment]
1.1.0 版本存在问题，需要手动导入WeexGcanvas相关文件，才可以运行，否则会提示 using unregistered weex module "gcanvas"

**Comment by jwxbond** [comment]
WeexPluginLoader库安装是否正常。 这个库是保证自动注册gcanvas组件的。

**Comment by Luis-X** [comment]
已经解决了，通过cocoaPods安装，发现没有WeexGcanvas相关的文件，WXGCanvasModule和WXGCanvasComponent手动导入就正常了
