### ISSUE TITLE
Difficulties integrating on React Native

### ISSUE THREAD

**Issue by grocco** [alibaba/GCanvas#14]
Hi there!

Congratulations for your effort. Can't wait to try this out.

I am developing a React Native app and followed the instructions to integrate GCanvas.

The steps were the following:
    npm install react-native-gcanvas --save
    nom install gcanvas.js --save
    react-native link react-native-gcanvas

When I

    react-native run-ios

or

    react-native run-android

.. I get build errors: 

In the case of iOS:

    CanvasView.h:12:9: fatal error: 'GCanvas/GCanvasViewProtocol.h' file not found

In Android:

    Extension with name 'sdks' does not exist. Currently registered extension names: [ext]

What are the pre-conditions to make it work?

I used to have Gradle plugin 2.2.1 and moved to 3.0.1, but still same issue.

Thanks a lot for your feedback!
Best,

OS: macOS High Sierra 10.13.2
Node: 6.11.1
npm: 3.10.10
Watchman: 4.7.0

react-native-cli: 2.0.1
react-native: 0.54.1

react-native-gcanvas : 0.01
gcanvas.js : ^0.05

**Comment by jwxbond** [comment]
Hi @grocco , thanks for following up.  About iOS, we missing `GCanvas.xcodeproj`, now we replace by  `GCanvas.framework`.  So you should update `react-native-gcanvas` to `0.0.2`, and then follow the latest guide https://github.com/alibaba/GCanvas/blob/dev/GCanvas/docs/Guide_Setup_ReactNative.md

**Comment by grocco** [comment]
Thanks a lot @jwxbond !

I tried to update `react-native-gcanvas` to `0.0.2`.

I also followed the steps shown in the new guide.
Now I get this error (the same one I got yesterday when I tried to import the GCanvas library on my own).

```
In file included from /<MY_PROJECT_PATH>/node_modules/react-native-gcanvas/ios/RCTGCanvasModule.m:23:
In file included from /Users/<MY_USERNAME>/Library/Developer/Xcode/DerivedData/<MY_PROJECT>-dhcptgcgqwqujkdxgzbkodkuiuwk/Build/Products/Debug-iphonesimulator/GCanvas.framework/Headers/GCanvasModule.h:22:
/Users/<MY_USERNAME>/Library/Developer/Xcode/DerivedData/<MY_PROJECT>-dhcptgcgqwqujkdxgzbkodkuiuwk/Build/Products/Debug-iphonesimulator/GCanvas.framework/Headers/GCVCommon.h:16:9: fatal error: 'GCVLog.h' file not found
#import "GCVLog.h"
        ^~~~~~~~~~
1 error generated.```

**Comment by jh3141** [comment]
I'm seeing the same Android error ... did you get this to work?

**Comment by grocco** [comment]
@jh3141 no, I did not get it to work for Android yet. Waiting for an update

**Comment by jwxbond** [comment]
@grocco    have you set `Framework Search Path`,  automatic installation Step 2:  " Add $(SRCROOT)/../node_modules/react-native-gcanvas/ios to your project's Build Settings ➜ Framework Search Path"

**Comment by fREEDtICE** [comment]
@grocc Still looking forward to it.

**Comment by grocco** [comment]
@jwxbond yes I did set it (and I tried both setting it both recursive or not). I must be missing something else which somehow is properly set up when using the command `react-native run-ios`

**Comment by jwxbond** [comment]
@grocco  please check "GCVLog.h" file exist  in  GCanvas.framework/Headers which used.  If not fetch it from branch `dev` again.

**Comment by DavidGOrtega** [comment]
I believe that for android is not implemented. See the issue I have opened #26

**Comment by fREEDtICE** [comment]
Hi @grocco, we have fixed issues about RN integration on Android, Please check our new guideline and try it again. Thanks.
https://alibaba.github.io/GCanvas/docs/Integrate%20GCanvas%20on%20ReactNative.html
