### ISSUE TITLE
invalid clipping

### ISSUE THREAD

**Issue by eco747** [alibaba/GCanvas#148]
in GPath::StencilRectForStroke
when checking path limits, if the path bump outside the view, the clipping is badly computed if any translation is set before and drawing color has alpha.

```cpp
if( rect.height > context->GetHeight() || rect.width > context->GetWidth() ) {
	rect.x = 0; <<<<<<<<< cannot use 0 because of translation
	rect.y = 0; <<<<<<<<< idem
	rect.width = context->GetWidth();
	rect.height = context->GetHeight();
}
```

can be checked with a js like that

```js

ctx.translate( 100, 100 );
ctx.moveTo( -10, -10 );
ctx.lineTo( 110, 110 );
ctx.strokeStyle( "rgba(255,0,0,0.5)" );
ctx.stoke( );

```

**Comment by jwxbond** [comment]
![image](https://user-images.githubusercontent.com/1164433/78961351-c1941280-7b23-11ea-8236-1fe73e7c9e53.png)

this case compare with web in iOS, result is match
