### ISSUE TITLE
Bad round cap drawing

### ISSUE THREAD

**Issue by eco747** [alibaba/GCanvas#149]
In some cases, in GPath::drawArcToContext,
the float rounding lead to acosf evaluate overflow values 

```cpp
angle2 = acosf( v1.x * v2.x + v1.y * v2.y );
```

should be replaced by 

```cpp
float v = v1.x * v2.x + v1.y * v2.y;
if( v < -1.0 ) {
	v = -1.0;
}
else if( v > 1.0 ) {
	v = 1.0;
}
angle2 = acosf( v );
```

**Comment by jwxbond** [comment]
hi eco747 , thank you for your attention to GCanvas . you can commit PR to fix issues as contributor ， that's  is welcome!

**Comment by eco747** [comment]
Hi,
how can i become a contibutor (i'm new to public github contribution) ?
i try to push a new branch but i got a 403 error; access denied.

Regards
Etienne

**Comment by jwxbond** [comment]
New pull request
