### ISSUE TITLE
Documentation error - no indication of how to install "gcanvas.js"

### ISSUE THREAD

**Issue by jh3141** [alibaba/GCanvas#15]
The installation guide for react-native suggests using `npm install react-native-gcanvas --save`, however this command doesn't install the required `gcanvas.js` module: in order to get this to work I also needed to run `npm install gcanvas.js --save`.

**Comment by jwxbond** [comment]
Hi @jh3141  thanks for following up. About this issue, we add update `react-native-gcanvas` to `0.0.3`  , and add dependency `gcanvas.js`
