### ISSUE TITLE
Feature request: measureText() Method for Grapics 2D context

### ISSUE THREAD

**Issue by grocco** [alibaba/GCanvas#17]
Hello there.

I am developing an app for which the `measureText()` method of the 2D context is vital.
I need to know the `width` of any given string using the current font (including any newspaces `\n`) to make sure it fits in the canvas.
It would be awesome to have that implemented in GCanvas.

Are you already working on it and have an idea of when it could be available?
Otherwise, if you have no time I'd be happy to contribute and implement it (would need a small introduction tho).

Thank you.

**Comment by fREEDtICE** [comment]
Hi, @grocco,
Thanks for following up GCanvas.  This is our roadmap for next 6 months:
1. Improve text rendering performance, especially for Android - Will release at early of May 2018
2. Draw other GCanvas as render target for 2D graphics - Will release at late of May 2018
3. Build a high-performance independent runtime container - Will release in July 2018

So GCanvas team can add `measureText` feature into text rendering version.

But if you are anxious,  I recommend that you implement it by yourself please, and we welcome you to contribute code.

Here's the idea about how to implement measure text:
1) Modify `js/src/context-2d/RenderingContext.js`,  add `measureText` function. Please notice that you should convert the function into a string command, and make sure the single command key is not used.
2) Modify 'execute2dCommands' in`GCanvas.cpp` which is under folder 'core/src', then do your implementations. Please notice that implementation of text rendering for Android and iOS is not the same. Android uses Freetype, while iOS calls System APIs.

If you have any questions, please feel free to ask. Thanks.

**Comment by grocco** [comment]
Thank you very much for sharing your roadmap and for the implementation suggestions!
I will let you know if I will work on it. I will first have to make sure I can afford using the library in my app at this stage given the current performance (I will open another issue about it as it is unrelated)
