### ISSUE TITLE
React Native: how to get good performance

### ISSUE THREAD

**Issue by grocco** [alibaba/GCanvas#19]
OS: macOS High Sierra 10.13.2
Node: 6.11.1
npm: 3.10.10
Watchman: 4.7.0

react-native-cli: 2.0.1
react-native: 0.54.1

react-native-gcanvas : 0.02
gcanvas.js : ^0.05

Simulator (ios): 10.0 (SimulatorApp-835.5 CoreSimulator-494.33) - iPhone 6 - 11.2 

I am writing an application where text is being rendered on the canvas whenever the user types in a `<TextInput />`. My`draw()` method is called whenever the text changes, which is, whenever the user types. I noticed that if on each call to `draw()` I execute `canvas.getContext("2D")`, the CPU starts going up and the iphone simulator becomes slow and irresponsive. By getting the canvas and saving the context in the state, and calling `getContext("2D")` only once, the performance is better, but still quite slow. In general though, even if I just do it once, as soon as I call `getContext("2D")` the CPU does rise quite a lot and stays high, even if the user is not typing.

**Comment by jwxbond** [comment]
@grocco ,  You case runs in debug environment with simulator?  You'd better use iPhone device to check performance about CPU. I have a test about sample `RNGCanvasSample` in Release with iPhone 6s Plus,  and click frequently to redraw the view .  The result CPU usage is about 13%-17%
