### ISSUE TITLE
Please check Gradle wrapper into git

### ISSUE THREAD

**Issue by nerfpops** [alibaba/GCanvas#21]
I tried copying a Gradle wrapper from another project and GCanvas gets compiled until it reaches the react native bridge, where the build is abortet:

```
Execution failed for task ':bridges:react-native-bridge:react-native-gcanvas:android:lint'.
> Lint found errors in the project; aborting build.

  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
```

The problem occurs because I have a different version of Gradle than the one you're using. It was easily solved by adding the suggested fix, but It is "expected" that the Gradle wrapper is committed to version control, as per [the docs](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:adding_wrapper):

> To make the Wrapper files available to other developers and execution environments you’ll need to check them into version control. All Wrapper files including the JAR file are very small in size. Adding the JAR file to version control is expected. Some organizations do not allow projects to submit binary files to version control. At the moment there are no alternative options to the approach.

**Comment by jwxbond** [comment]
invalid

**Comment by jwxbond** [comment]
invalid
