### ISSUE TITLE
Can't compile GCanvas due to error in Weex playground project

### ISSUE THREAD

**Issue by nerfpops** [alibaba/GCanvas#22]
When building GCanvas by running `./GCanvas/GCanvas/gradlew build`, and after disabling linting errors for the react native bridge, I receive the following error:

```
Execution failed for task ':bridges:weex-bridge:android:weex_playground:transformNativeLibsWithMergeJniLibsForDebug'.
> More than one file was found with OS independent path 'lib/armeabi/libgcanvas.so'
```

I'm compiling on Windows.

**Comment by hejian1639** [comment]
1. open this file GCanvas/android/gcanvas_library/build.gradle
2. remove line 67-84
3. delete build folder
4. build

**Comment by nerfpops** [comment]
I just removed weex_playground from the build, but shouldn't the project be able to compile without such steps?

**Comment by jwxbond** [comment]
Now Weex Playground is support gcanvas, or you can use GCanvasPlayground https://github.com/alibaba/GCanvas/tree/master/packages/weex-gcanvas
