### ISSUE TITLE
Working demo on Expo.io

### ISSUE THREAD

**Issue by DavidGOrtega** [alibaba/GCanvas#25]
Hi,

I have tried the demo on [my snack expo](https://snack.expo.io/@davidgortega/gcanvas-test) without luck.

I have the following error:

```
Device: (1068:6932) Failed to install module 'react-native-gcanvas': Tried to register two views with the same name RCTGCanvasView
```

Any ideas?

**Comment by hejian1639** [comment]
please try to use below code
`var RCTGCanvasView = requireNativeComponent('GCanvasView');`

**Comment by DavidGOrtega** [comment]
Hi @hejian1639 I have followed your instructions in the expo snack but I have the same issue.

You can ty it [here](https://snack.expo.io/@davidgortega/gcanvas-test) in case that you want to test it personally. I'm using gcanvas.js and react-native-gcanvas from npm.

**Comment by DavidGOrtega** [comment]
Hi, with the new update (0.0.6) I have tried in [expo again](https://snack.expo.io/ByfbDpFjf) and the error is different:

````
Error: "Invariant Violation: View config not found for name GCanvasView This error is located at: in GCanvasView in t in RCTView in TouchableHighlight in RCTView in App in RCTView in RCTView in t in t in r in RCTView in RCTView in t" in exports@/data/data/host.exp.exponent/files/26.0.0/cached-bundle-experience-%40snack%2FHJ9d63YjM-2143420360-26.0.0:17:309 << createInstance@/data/data/host.exp.exponent/files/26.0.0/cached-bundle-experience-%40snack%2FHJ9d63YjM-2143420360-26.0.0:44:69648 << completeWork@/data/data/host.exp.exponent/files/26.0.0/cached-bundle-experience-%40snack%2FHJ9d63YjM-2143420360-26.0.0:44:47204 << t@/data/data/host.exp.exponent/files/26.0.0/cached-bundle-experience-%40snack%2FHJ9d63YjM-2143420360-26.0.0:44:56029 ...
```

**Comment by DavidGOrtega** [comment]
Snack Expo is not building native library.
