### ISSUE TITLE
Playground APK does not work

### ISSUE THREAD

**Issue by DavidGOrtega** [alibaba/GCanvas#28]
Hi

the [gcanvas playgroung app](https://raw.githubusercontent.com/g-platform/gcanvas-playground-android/master/weex_playground-debug.apk) can not be installed.

Tested on:
Meizu Note 3 : says For test only, please install official version
One plus 3 : says that the app is corrupted

**Comment by DavidGOrtega** [comment]
Is there any chance to review this? Or at least, where can I find the source code of the playground app?

**Comment by fREEDtICE** [comment]
@DavidGOrtega Follow the path "GCanvas/bridges/weex-bridge/android/weex_playground" will get the source code of the playground app
