### ISSUE TITLE
资源占用率高，建议提供对比测试数据

### ISSUE THREAD

**Issue by ipader** [alibaba/GCanvas#3]
1. CPU 资源占用： 25%  上下
2. 对能耗的影响： 150 上下

设备：2016 MacBook Pro 13''
浏览器： Safari
运行示例：https://alibaba.github.io/GCanvas/

**Comment by wintercn** [comment]
是说网站？

**Comment by ipader** [comment]
是的。网站示例是用了这套 API 的吧？

**Comment by fREEDtICE** [comment]
在PC上访问是使用的是WebView的Canvas

**Comment by wintercn** [comment]
GCanvas是移动端的canvas实现，网站用的是普通canvas

**Comment by fREEDtICE** [comment]
这个问题先关闭了，@ipader同学如果有疑问可以给我们发邮件。谢谢。
