### ISSUE TITLE
Build fails on iOS and Android

### ISSUE THREAD

**Issue by jordansexton** [alibaba/GCanvas#31]
**iOS**

Build fails with 

> ./node_modules/react-native-gcanvas/ios/RCTGCanvasView.h:23:9: 'GCanvas/GCanvasViewProtocol.h' file not found

Following the latest docs (and using `react-native-gcanvas` v `0.0.5` and `gcanvas` v `0.0.7`), there is no `./node_modules/react-native-gcanvas/ios/GCanvas.framework` file (after running `react-native link react-native-gcanvas`).

**Android**

Build fails with

> Extension with name 'groups' does not exist. Currently registered extension names: [ext]

Relevant line is `group = rootProject.extensions.groups.Bridge` in `./node_modules/react-native-gcanvas/android/build.gradle`. Gradle version is 3.1.0.

**Comment by jwxbond** [comment]
@jordansexton  thanks for following up.  About iOS  `react-native-gcanvas` have a new update to `0.0.6`,  and please try it again.

**Comment by fREEDtICE** [comment]
@jordansexton Please use our aar maven version. Please check our document below:
https://alibaba.github.io/GCanvas/docs/Integrate%20GCanvas%20on%20ReactNative.html

**Comment by jordansexton** [comment]
@jwxbond Thank you! I was able to get the iOS build finished with `0.0.6` which has the required file and following the iOS steps from the documentation.

@fREEDtICE I followed all the Android steps in that document before arriving at that error, but I'll try again from scratch using the latest version.

**Comment by jordansexton** [comment]
The Android section of the RN setup seem to be missing a few things. These lines all throw errors:

https://github.com/alibaba/GCanvas/blob/ccba24603861d47f5c72b9f223b07d018936c36f/GCanvas/bridges/react-native-bridge/react-native-gcanvas/android/build.gradle#L3-L12

https://github.com/alibaba/GCanvas/blob/ccba24603861d47f5c72b9f223b07d018936c36f/GCanvas/bridges/react-native-bridge/react-native-gcanvas/android/build.gradle#L28-L31

I'm guessing the issue is that these libraries

https://github.com/alibaba/GCanvas/tree/master/GCanvas/android

are not being included by the `react-native-gcanvas` or `gcanvas.js` npm packages.

Additionally, whatever setup config is supposed to be there for `rootProject.extensions.<etc>` to be defined won't be there for existing RN projects.

**Comment by fREEDtICE** [comment]
Hi, @jordansexton,  RN projects have their own root project if created by "react-native init" command. You can check setting.gradle, it re-defined rootProject.

If you build GCanvas RN bridge under GCanvas Repo Project, it should work. 
 
We will delete Android source code in the react-native-gcanvas npm package, replace it with aar package later. Right now please use our aar dependency for compiling. Thanks.

**Comment by jordansexton** [comment]
Unfortunately building it inside the repo project without other documentation on installation as a library in my project isn't a practical option. I also wasn't able to get substantially better performance on iOS than just using an HTML canvas in a WebView.

I'll reevaluate when there's more documentation and tests, but thank you for your help and your work on this. I think it's a really interesting project and I'm excited to see how it progresses.

**Comment by Micjoyce** [comment]
Now, what are some ways to make android work? I tried to  run the react native example below the bridge and it dons't work.

**Comment by IvenOne** [comment]
Any solutions？

**Comment by nvwebm** [comment]
What about it?

**Comment by goodgoodbigbig** [comment]
Any solutions？

**Comment by Mystify76** [comment]
Any progress on this issue? I am getting a problem when trying to run on android with `rootProject.extensions.sdks.Support`

**Comment by likern** [comment]
> Any progress on this issue? I am getting a problem when trying to run on RN android with `rootProject.extensions.sdks.Support`

Have you finally solved this issue? I've recently came across with this error and can't find a way to fix or avoid it.

**Comment by TryAgainLater** [comment]
> 
> 
> > Any progress on this issue? I am getting a problem when trying to run on RN android with `rootProject.extensions.sdks.Support`
> 
> Have you finally solved this issue? I've recently came across with this error and can't find a way to fix or avoid it.

Same for me: 
A problem occurred evaluating project ':react-native-gcanvas'.
Extension with name 'sdks' does not exist.

**Comment by arturz** [comment]
Problem still occurs.

**Comment by uniquecolin** [comment]
RN bridge has been removed

**Comment by flyskywhy** [comment]
@jordansexton @Micjoyce @IvenOne @nvwebm @goodgoodbigbig @Mystify76 @likern @TryAgainLater @arturz @uniquecolin 

Since Alibaba [feat: delete weex bridge & reactive bridge](https://github.com/alibaba/GCanvas/commit/1bbee40a16c0c5da58698e2892ba33f836eedb70), here comes the [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) npm package.

After months work, [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) runs well on Android and iOS, fix several bugs and add `feat: support drawImage() from require('some.png') on Android, iOS and Web` described in [Changelog.md](https://github.com/flyskywhy/react-native-gcanvas/blob/master/docs/Changelog.md), refactor with the detailed [Example As Usage](https://github.com/flyskywhy/react-native-gcanvas#example-as-usage) in README.md.

With [Performance Test Result](https://github.com/flyskywhy/react-native-gcanvas#performance-test-result), and [Convenient With Browser-like canvas APIs](https://github.com/flyskywhy/react-native-gcanvas#convenient-with-browser-like-canvas-apis) with the easily `<canvas/>` ported example [react-native-particles-bg](https://github.com/flyskywhy/react-native-particles-bg) runs on Android, iOS and Web, `@flyskywhy/react-native-gcanvas` is the best choice for now :yum:

**Comment by arthare** [comment]
@flyskywhy Dude!  Awesome!  I got it working in minutes, and it's way faster than the webview+canvas solution I had before.  Plus, you know, it compiles on android :-)

**Comment by devansh-nigam** [comment]
The issue still persists, 

```
A problem occurred evaluating project ':react-native-gcanvas'.
> Extension with name 'sdks' does not exist. Currently registered extension names: [ext, _internalAndroidGradlePluginDependencyCheckerRegistered]
```

**Comment by danbudworthmead** [comment]
> The issue still persists,
> 
> ```
> A problem occurred evaluating project ':react-native-gcanvas'.
> > Extension with name 'sdks' does not exist. Currently registered extension names: [ext, _internalAndroidGradlePluginDependencyCheckerRegistered]
> ```

did you ever find a fix?

**Comment by UmarLE** [comment]
> The issue still persists,
> 
> ```
> A problem occurred evaluating project ':react-native-gcanvas'.
> > Extension with name 'sdks' does not exist. Currently registered extension names: [ext, _internalAndroidGradlePluginDependencyCheckerRegistered]
> ```

did anybody find solution for it.
