### ISSUE TITLE
Usage guide missing code causes NRE

### ISSUE THREAD

**Issue by jordansexton** [alibaba/GCanvas#32]
This is in reference to the **Usage** section @ https://alibaba.github.io/GCanvas/docs/Integrate%20GCanvas%20on%20ReactNative.html

The code is importing `NativeModules` but seems to be missing something like
```
ReactNativeBridge.GCanvasModule = NativeModules.GCanvasModule;
```

The call stack `enable` --> `GBridge.callEnable` --> `GBridge.GCanvasModule.enable` fails with a null reference error on `GCanvasModule`.

I don't know if this should be in the documentation for use, or in the file `gcanvas.js/src/bridge/bridge-reactnative.js`, since it's a prerequisite for anything working.

**Comment by fREEDtICE** [comment]
@jordansexton 
`
ReactNativeBridge.GCanvasModule = NativeModules.GCanvasModule;
ReactNativeBridge.Platform = Platform;
`
Please add the two lines after "import" statements.

**Comment by jordansexton** [comment]
Got it. Thanks!
