### ISSUE TITLE
mismatch between gcanvas.js and weex-gcanvas module(IOS)

### ISSUE THREAD

**Issue by danniss** [alibaba/GCanvas#33]
Hi, I'm using the gcanvas.min.js( compiled from source) and weex-gcanvas(installed using cocoapods).
I found the interfaces between gcanvas.js and weex module are not consistent.
eg,  the gcanvas.js  is calling the bindImageTexture interface like this: 

`GCanvasModule.bindImageTexture([src, imageId], componentId);`

The first param is an array, while the same interface implemented in WXGCanvasModule.m:

`- (void)bindImageTexture:(NSString*)src componentId:(NSString*)componentId callback:(WXModuleCallback)callback`

the first param is a string.

so obviously this won't work. Probably I should not use the latest gcanvas.js, but AFAIK, there is no way to install gcanvas.js that matches the version of weex-gcanvas. "npm install weex-gcanvas" does not give me the right gcanvas.js.

This is not a flaw in code, but somebody should update the package.

**Comment by danniss** [comment]
@jwxbond Thanks for the reply.
I was specifying a relatively low deployment target, which is ios 7.0. So the latest WeexGcanvas version did not apply.  After change it to ios 9.0, everything works like a charm. 

I suggest you add this into docs, in case someone has bad luck like me :)

Thanks dude.

**Comment by jwxbond** [comment]
@danniss  you can make an update and commit a PR about it
