### ISSUE TITLE
站点文档标题与G3D混淆

### ISSUE THREAD

**Issue by jay7n** [alibaba/GCanvas#35]
https://alibaba.github.io/GCanvas/docs/Introduction.html

<img width="320" alt="default" src="https://user-images.githubusercontent.com/1228472/38907748-d24a8f82-42ef-11e8-924a-526055967b09.png">

以及关联的所有网页，其标题都以G3D开头，但内容却是GCanvas的

**Comment by xieguanglei** [comment]
Thanks, it will be fixed soon.
