### ISSUE TITLE
React Native calling synchronous methods on native module is not supported in Chrome

### ISSUE THREAD

**Issue by Micjoyce** [alibaba/GCanvas#36]
The chrome debugger complains if you make synchronous native calls. Please add asynchronous alternatives.

![image](https://user-images.githubusercontent.com/4250838/38977690-aad91b32-43e7-11e8-9870-0038f16283f9.png)

**Comment by nanndoj** [comment]
+1 
This issue is a blocker to use the debugger

**Comment by KongfuMan** [comment]
Same issue! After I use the react-devtools, everything is fine.

**Comment by MoeMamdouh** [comment]
Is there any way to enable debug while using this library?
