### ISSUE TITLE
Question: what is the benefit of GCanvas

### ISSUE THREAD

**Issue by LinBoLen** [alibaba/GCanvas#39]
webgl based on opengl es afaik, the GCanvas also based on opengl es. so what is the benefit of GCanvas better than webgl.

**Comment by fREEDtICE** [comment]
1. GCanvas is a Rendering engine with W3C standard API designs.  It can be integrated into any Javascript-capable environment, which WebGL can only run in WebView.
2. GCanvas is not a WebView DOM. It does not follow the WebView rendering procedure, which gives GCanvas high performance than WebView canvas.
