### ISSUE TITLE
华为荣耀8手机文本渐变填色不支持

### ISSUE THREAD

**Issue by shadowGdNf** [alibaba/GCanvas#4]
var ref = this.$refs.canvas_holder;
      ref = enable(ref, {bridge: WeexBridge});
      var ctx = ref.getContext('2d');

      ctx.font="20px Georgia";
      ctx.strokeText("Hello World!",10,50);

      ctx.font="30px Verdana";
      // 创建渐变
      var gradient=ctx.createLinearGradient(0,0,300,0);
      gradient.addColorStop("0","magenta");
      gradient.addColorStop("0.5","blue");
      gradient.addColorStop("1.0","red");
      // 用渐变填色
      ctx.strokeStyle=gradient;
      ctx.strokeText("Hello World2222222!",10,90);
执行上述代码在华为荣耀8手机上不显示下面的"Hello World2222222!"，小米4c和锤子手机正常。

**Comment by fREEDtICE** [comment]
@sylonhu 请胡老师处理下这个问题

**Comment by gujianglai** [comment]
看上去android的strokeText并没有实现完整，文字镂空同样有问题，GCanvasContext::FillText方法android实现中isStroke入参根本没有用到；关联的GFont类的私有变量mOutlineType只有一个初值0，并没有其他地方进行赋值

**Comment by finscn** [comment]
Is there any news about this issue , @fREEDtICE  @gujianglai  ?

**Comment by jwxbond** [comment]
Fixed at latest version
