### ISSUE TITLE
WebGL 的`getContextAttributes` 真的非常重要, 希望能早日支持. 

### ISSUE THREAD

**Issue by finscn** [alibaba/GCanvas#48]
很多webgl框架/引擎 都要用到这个方法, 来做一些webgl特性的检查.没有这个函数 很多框架没法正常运行.
希望早日支持.

**Comment by jwxbond** [comment]
Weex Component的机制对同步调用支持不是很好，后续会推出JSBinding的方案，同步调用的方法能很好的支持了

**Comment by jwxbond** [comment]
weex下的类似同步接口的问题先关闭了。
