### ISSUE TITLE
iOS 8系统上canvas竖线不显示

### ISSUE THREAD

**Issue by zdpdsy** [alibaba/GCanvas#5]
调用strokeRect方法或者closePath方法 ，在iOS 8手机上发现竖线不显示，iOS8以上系统机型显示正常
代码如下:
` var ref = this.$refs.canvas_holder;

      ref = enable(ref, {bridge: WeexBridge});
     
      var ctx = ref.getContext('2d');
      ctx.strokeRect(20,20,150,100);
`

` var ref = this.$refs.canvas_holder;
      ref = enable(ref, {bridge: WeexBridge});
      var ctx = ref.getContext('2d');

      ctx.beginPath();
      ctx.moveTo(20,20);
      ctx.lineTo(20,100);
      ctx.lineTo(70,100);
      ctx.closePath();
      ctx.stroke();
`
![image](https://user-images.githubusercontent.com/7123339/37135560-bec630b0-22d8-11e8-87b6-2216200c8530.png)

**Comment by zdpdsy** [comment]
目前我这边是在前端canvas.js做了一个判断，
![image](https://user-images.githubusercontent.com/7123339/37137921-ec53b5c0-22e2-11e8-8800-6da94aff3714.png)
规避了这个问题。希望能从native实现上去解决这个问题。

**Comment by jwxbond** [comment]
fix it, lineWidth problem. see more detail https://github.com/alibaba/GCanvas/commit/07662bec98b0ce0a6eac319c0a57a2a019eceecb

**Comment by jwxbond** [comment]
@zdpdsy iOS版本并非主要问题，iOS10以上iPhone 5c的环境也同样你说的问题。是设备尺寸 和 绘制过程中线宽处理两方面的原因造成。 该问题已经修复，详见：https://github.com/alibaba/GCanvas/commit/07662bec98b0ce0a6eac319c0a57a2a019eceecb

**Comment by zdpdsy** [comment]
好的，已测试过可以的，谢谢 @jwxbond
