### ISSUE TITLE
library not found for -lRCTGCanvas

### ISSUE THREAD

**Issue by nanndoj** [alibaba/GCanvas#51]
I am using the react native bridge and it is working fine in Debug Scheme, but I get the following error when I try to Archive the project in xcode or generate a Release build:

### Current behavior
when building the project for release:
````
xcodebuild "-project" "ios/BetClash.xcodeproj" "-scheme" "BetClash" "-configuration" "Release" "archive" "-verbose" | xcpretty
`````

The linker fails with:

````
ld: library not found for -lRCTGCanvas
````

### Expected behavior

It should build without errors.

### Env:
`````
node: v9.11.2
npm: 5.6.0
xcode: 9.4.1
`````

**Comment by pailjin** [comment]
in xcode, click the RCTGCanvas project in Libraries dir, change the build target version to same as your project target.
for example, your project build target version is ios 11.0, then change RTCGCanvas.xcodeproj to same.

**Comment by JeffGuKang** [comment]
Refer https://stackoverflow.com/a/58566191/515932
