### ISSUE TITLE
integrate three.js in a GCanvasView : Error Renderer

### ISSUE THREAD

**Issue by nathanfrad** [alibaba/GCanvas#56]
I'm trying to render a scene **three.js** in a **GCanvasView**. But it doesn't work... 
I can display shapes in webgl and 2D but not with Three.js.
The function that does not work with three.js is the function **WebGLRenderer**().

```

let ref = this.refs.canvas_holder;
let canvas_tag = findNodeHandle(ref);
// var canvas_tag = "2";
let el = {ref: "" + canvas_tag, style: {width: 414, height: 376}};
ref = enable(el, {bridge: ReactNativeBridge});

//Webgl
let gl = ref.getContext('webgl');
gl.clearColor(0.0, 0.0, 0.0, 1.0);
gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);

var renderer = new THREE.WebGLRenderer({canvas: ref});
renderer.setSize( 800, 640 );
var scene = new THREE.Scene();
```

I've already tried integrating three.js into React native with the react-native-webgl library. The rendering of the scene worked but I couldn't control the camera... So I'm trying Gcanvas

**Config:**
react-native-cli: 2.0.1
react-native: 0.55.4

**Error** 
_console.error: "THREE.WebGLRenderer: _canvas.addEventListener is not a function.
(in '_canvas.addEventListener('webglcontextlost', onContextLost , false)',
'_canvas.addEventListener' is undefined)'_

The functions that trigger the **error** are in the file three.module.js ( /node_modules/three/build/three.module.js)

```
// event listeners must be registered before WebGL context is created, see #12753
_canvas.addEventListener( 'webglcontextlost', onContextLost, false );
_canvas.addEventListener( 'webglcontextrestored', onContextRestore, false );

```
At first I thought that Gcanvas did not accept the **addEventListener()** function. But after searching in the Gcanvas repository, I found the same function in the **Gimage** class ( GCanvas/GCanvas/js/src/env/image.js) that called when `var image = new GImage();`

**Do you have an idea to render three.js in a Gcanvas view? Thanks**

![image](https://user-images.githubusercontent.com/25525238/43569720-9b2895b6-9638-11e8-9bc2-b6c8e49221bc.png)

**Comment by nathanfrad** [comment]
+1

**Comment by Kielan** [comment]
https://www.decoide.org/react-native/docs/appstateios.html

**Comment by jwxbond** [comment]
three.js is not support now, and js binding will be support later
