### ISSUE TITLE
Uncaught ReferenceError: callGCanvasLinkNative is not defined

### ISSUE THREAD

**Issue by xtich** [alibaba/GCanvas#59]
//              gcanvas       7.2 add
    compile "com.taobao.gcanvas:corelib:1.0.4"
    compile "com.taobao.gcanvas.adapters:img:1.0.0"
    compile "com.taobao.gcanvas.bridges:spec:1.0.1"
    compile "com.taobao.gcanvas.bridges:weex:1.0.2"
    compile "com.taobao.gcanvas.adapters:img_fresco:1.0.1"

   gcanvas     7.2  add
            WXSDKEngine.registerModule("gcanvas", GCanvasWeexModule.class);
            WXSDKEngine.registerComponent("gcanvas", WXGCanvasWeexComponent.class);

    
    <uses-feature android:glEsVersion="0x00020000" />

**Comment by dufangyu1990** [comment]
我也遇到这个问题了，请问该怎么解决
