### ISSUE TITLE
react native 闪退

### ISSUE THREAD

**Issue by tamamadesu** [alibaba/GCanvas#7]
这是运行的环境参数：
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0

  react-native-gcanvas  : 0.01
  gcanvas.js : 0.06

用的 link 方式 关联项目： react-native link react-native-gcanvas

然后试运行了官网给的例子，只要加上GCanvasView 就会闪退，或者目前项目只能运行在RN某个版本？还是有其他问题？

**Comment by jwxbond** [comment]
@tamamadesu  dev最新的分支，进入react-native-bridge/examples/RNGCanvasSample目录。 执行 npm install后，就可以用模拟器或则真机上运行 ios/RNGCanvasSample.xcodeproj 这个例子。  也尝试你提供的版本依赖，按照上述的操作也能正常运行。

**Comment by tamamadesu** [comment]
@jwxbond  谢谢回复，我clone试下！
