### ISSUE TITLE
is quadraticCurveTo work?

### ISSUE THREAD

**Issue by dourgulf** [alibaba/GCanvas#71]
iOS simulator, gcanvas.js version is "0.0.8",
GCanvas pod installed version is "0.1.2"
Testing code with  Weex-bridge.
Following draw code:
```JavaScript
    ctx.moveTo(0,200);
    ctx.quadraticCurveTo(75,50,300,200);
    ctx.stroke();
```
this code only show me a poly-line(start point to control point and control point to end point), not a curve.

**Comment by dourgulf** [comment]
我提交了一个PR解决这个问题https://github.com/alibaba/GCanvas/pull/72。
问题的原因应该是mCurrentState->mTransform现在不是单位矩阵（未增加变换之前）而是投影矩阵，它算出来的scale值非常的小，导致传进去之后，执行递归的二次贝塞尔曲线的“可接受误差”很大，只执行了一次递归就结束了。
解决办法是重新从投影矩阵求算回正确的x，y坐标轴的scale大小，取其中更大的一个做参数。

**Comment by jwxbond** [comment]
Fixed
