### ISSUE TITLE
iOS SendVertexBufferToGPU Crash

### ISSUE THREAD

**Issue by jianxiongc** [alibaba/GCanvas#79]
在iOS 渲染成功后放置几分钟再这里崩溃
`
GCanvas2dContext.cpp
void GCanvasContext::SendVertexBufferToGPU(const GLenum geometry_type)
{
    if (mVertexBufferIndex == 0)
    {
        return;
    }

    glDrawArrays(geometry_type, 0, mVertexBufferIndex);  // Crash Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)
    mVertexBufferIndex = 0;
}
`

**Comment by jwxbond** [comment]
问题已修复

**Comment by MoeMamdouh** [comment]
its happens with me #111
