### ISSUE TITLE
pod install 时RPC failed; curl 18 transfer closed with outstanding read data remaining

### ISSUE THREAD

**Issue by wangxuewen** [alibaba/GCanvas#88]
```
Cloning into '/var/folders/gr/3pwv50y90db54sygb37d32jh0000gn/T/d20190516-20599-zlv2rk'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```
加大httpBuffer依旧拉不下来

**Comment by jwxbond** [comment]
哪个库下载失败了？

**Comment by jwxbond** [comment]
检查下环境，使用最新的应该没有问题

**Comment by huilongquan** [comment]
i face the same issue.

**Comment by flyskywhy** [comment]
@wangxuewen  @huilongquan  ，参见 [使用 Cocoapods 安装 iOS 第三方库](https://github.com/flyskywhy/g/blob/master/i%E4%B8%BB%E8%A7%82%E7%9A%84%E4%BD%93%E9%AA%8C%E6%96%B9%E5%BC%8F/t%E5%BF%AB%E4%B9%90%E7%9A%84%E4%BD%93%E9%AA%8C/%E7%94%B5%E4%BF%A1/Tool/%E7%BC%96%E7%A8%8B%E8%AF%AD%E8%A8%80/JavaScript/React%E4%BD%BF%E7%94%A8%E8%AF%A6%E8%A7%A3.md#%E4%BD%BF%E7%94%A8-cocoapods-%E5%AE%89%E8%A3%85-ios-%E7%AC%AC%E4%B8%89%E6%96%B9%E5%BA%93) 中关于 “清华大学开源软件镜像站 CocoaPods 镜像使用帮助” 的说明
