### ISSUE TITLE
weex   ref = undefined

### ISSUE THREAD

**Issue by shimminZ** [alibaba/GCanvas#92]
<div  style="background-color: #1ba1e2">
        <gcanvas @touchstart="touchstart" @touchmove="touchmove" @touchend="touchend" ref="gcanvess"
              style="width: 650px;height: 1000px;background-color: yellow;margin-left: 50px"></gcanvas>
      </div>

我在div中设置了ref =  gcanvess，但是通过ref找对应的组件却提示找不到。
 var ref=self.$refs.gcanvess;

**Comment by shimminZ** [comment]
![WeChata5d6d0144442cb0487fddb0ead775c6b](https://user-images.githubusercontent.com/16769906/61507984-9b20cb00-aa1a-11e9-9559-49cbe6b022e2.png)

**Comment by jwxbond** [comment]
再检查下环境是否有问题

**Comment by jwxbond** [comment]
未重现该问题
