### ISSUE TITLE
android weex高版本GCanvas不支持么？

### ISSUE THREAD

**Issue by XMWP** [alibaba/GCanvas#93]
我用weex0.26.0版本依赖GCanvas报错，效果也显示不出来！报错
/weex: WXComponentFactory Exception type:[gcanvas] java.lang.NoClassDefFoundError: Failed resolution of: Lcom/taobao/weex/dom/WXDomObject;

**Comment by jwxbond** [comment]
已经与最新的Weex版本把持同步更新

**Comment by XMWP** [comment]
> 已经与最新的Weex版本把持同步更新
我是更新最新版本weexSDK？还是更新gcanvas:？
目前我看gcanvas:最新依赖还是旧版本的如下
  corelib compile "com.taobao.gcanvas:corelib:1.0.4"
 compile "com.taobao.gcanvas.adapters:img:1.0.0"
 compile "com.taobao.gcanvas.bridges:spec:1.0.1"
 compile "com.taobao.gcanvas.bridges:weex:1.0.2"
