### ISSUE TITLE
使用antv F2基于GCanvas绘图偶现一条射线

### ISSUE THREAD

**Issue by iquejay** [alibaba/GCanvas#94]
![绘图异常](https://user-images.githubusercontent.com/17787288/67288165-09d85d80-f50f-11e9-8663-14018fd5cb32.png)
如图 偶现绘图时出现一条异常的射线
- 使用的是weex、antv F2（V3.2.4）、GCanvas()
- 目前出现问题机型 华为P20 Pro、华为mate20、荣耀Magic2....都是华为手机

**Comment by jwxbond** [comment]
麻烦提供下case，Weex和GCanvas版本等信息，方便排查。

**Comment by iquejay** [comment]
> 麻烦提供下case，Weex和GCanvas版本等信息，方便排查。

之前是折线图偶现，后来发现线条设置为`line.shape("smooth")`的时候异常现象特别明显且更容易复现。   
上传了一个demo，[weex-gcanvas-f2 demo](https://github.com/iquejay/weex-gcanvas-f2) ，该demo使用的版本weex sdk 0.18.0、gcanvas 为[官网所给的android依赖版本](https://alibaba.github.io/GCanvas/docs/Integrate%20GCanvas%20on%20Weex.html)。   
补充上面最初遇到问题项目使用的版本信息：weex sdk 0.20.0、gcanvas  488b96a（Commits on Jan 8, 2019）
希望能尽快帮忙修复

**Comment by newaowen** [comment]
@jwxbond  此问题应该已FIX
