### ISSUE TITLE
GCanvas on ReactNative 安装配置完后，报错

### ISSUE THREAD

**Issue by ruixue521** [alibaba/GCanvas#96]
mac：10.14.4
xcode：Version 11.2 (11B52)
    "gcanvas.js": "0.0.8",
    "react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-gcanvas": "0.0.7-dev"

编译ios端时报错：  'React/RCTView.h' file not found

![image](https://user-images.githubusercontent.com/16204263/68276880-f4d00280-00a8-11ea-8473-d5734111528c.png)

**Comment by jwxbond** [comment]
使用 examples/RNGCanvasSample 来构建工程，里面会引用RCTGCanvas这个工程

**Comment by JeffGuKang** [comment]
Add `$(SRCROOT)/../../../ios/Pods/Headers` in `Youar XCode Project/Libraries/RCTGCanvas.xcodeproj => Build Settings => header Search Paths`
