### ISSUE TITLE
运行报异常：exception function:gcanvas setBackGround for android view, exception:WX_RENDER_ERR_TEXTURE_SETBACKGROUND: TextureView doesn't support displaying a background drawable!

### ISSUE THREAD

**Issue by huangzhiyuan0808** [alibaba/GCanvas#99]
下载源文件后，在uniapp直接运行时，
安卓手机运行环境下，报异常，canvas默认是透明底
ios运行正常，canvas是白色底
exception function:gcanvas setBackGround for android view, exception:WX_RENDER_ERR_TEXTURE_SETBACKGROUND: TextureView doesn't support displaying a background drawable!

**Comment by luckzhiwei** [comment]
能否给出调用案例？方便我们进行排查。比如如何android上怎么调用的gcanvas？

**Comment by huangzhiyuan0808** [comment]
使用的uniapp，工具使用的是HBuilderX,&nbsp; &nbsp;
gcanvas示例网址“https://github.com/dcloudio/NvueCanvasDemo”，克隆下来直接在开发工具里运行
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"廖志伟"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 中午1:52
收件人:&nbsp;"alibaba/GCanvas"<GCanvas@noreply.github.com&gt;;
抄送:&nbsp;"X    つ`"<664917175@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/GCanvas] 运行报异常：exception function:gcanvas setBackGround for android view, exception:WX_RENDER_ERR_TEXTURE_SETBACKGROUND: TextureView doesn't support displaying a background drawable! (#99)




能否给出调用案例？方便我们进行排查。比如如何android上怎么调用的gcanvas？
